variables:
  PYTHONUNBUFFERED: 1

stages:
  - test
  - push_code

jobs:
  test:
    stage: test
    image: python:3.13
    before_script:
      - pip install --upgrade pip
      - pip install -r requirements.txt
    script:
      - pytest -v
    only:
      - test

  push:
    stage: push_code
    image: alpine:latest
    before_script:
      - apk add --no-cache git bash
      - git config --global user.email "ci@example.com"
      - git config --global user.name "CI Bot"
    script:
      - git remote set-url origin https://PanMax13:glpat-xURJIJZEXKd3uKOvXgG1WWM6MQpvOjEKdTpsYmNidQ8.01.171erj410@gitlab.com/PanMax13/fastapi-currency-converter.git
      - git fetch origin
      - git checkout test
      - git merge origin/test --no-ff -m "Auto push to test after successful tests"
      - git push origin main
    needs:
      - test